version: '3' 
services: 
 
 
  reverse_proxy: 
    image: jwilder/nginx-proxy 
    restart: always 
    ports: 
      - "8080:8080" 
      - "8081:8081" 
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - ./nginx.conf:/etc/nginx/nginx.conf 
 
 
 
  apache_WS_1: 
    depends_on: 
      - reverse_proxy      
    image: httpd:alpine  
    volumes: 
      - ./HTML:/usr/local/apache2/htdocs
      #- ./WEB:/etc/nginx/nginx.conf
    restart: always 
 
 
  apache_WS_2:      
    image: httpd:2.4 
    volumes: 
      - ./HTML2:/usr/local/apache2/htdocs 
    # environment: 
    #   VIRTUAL_HOST: "www.google.com/web2" 
    #   VIRTUAL_PORT: 8000 
    restart: always